In [63]:
#Defining functions for modularization
def mean(data):
  sum = 0;
  i = 0;
  for num in data:
    sum = sum + num
    i = i+1
  return sum/i


def variance(data):
  n = len(data)
  if n == 0:
    return 0

  # Calculate the mean
  mean_val = mean(data) # Using the previously defined mean function

  # Calculate the sum of squared differences from the mean
  sum_sq_diff = 0
  for num in data:
    sum_sq_diff += (num - mean_val)**2

  return sum_sq_diff / n

In [69]:
#A1
import pandas as pd
d = pd.read_csv("Lab Session Data(Purchase data).csv")
df = pd.DataFrame(d)
df

,Customer,Candies (#),Mangoes (Kg),Milk Packets (#),Payment (Rs)
0,C_1,20,6,2,386
1,C_2,16,3,6,289
2,C_3,27,6,2,393
3,C_4,19,1,2,110
4,C_5,24,4,2,280
5,C_6,22,1,5,167
6,C_7,15,4,2,271
7,C_8,18,4,2,274
8,C_9,21,1,4,148
9,C_10,16,2,4,198


In [32]:
import numpy.linalg as lin
import numpy as np

Y = np.loadtxt(
    "Lab Session Data(Purchase data).csv",
    delimiter=",",
    skiprows=1,
    usecols=(1,2,3,4)
)

Y


array([[ 20.,   6.,   2., 386.],
       [ 16.,   3.,   6., 289.],
       [ 27.,   6.,   2., 393.],
       [ 19.,   1.,   2., 110.],
       [ 24.,   4.,   2., 280.],
       [ 22.,   1.,   5., 167.],
       [ 15.,   4.,   2., 271.],
       [ 18.,   4.,   2., 274.],
       [ 21.,   1.,   4., 148.],
       [ 16.,   2.,   4., 198.]])

In [31]:
import csv
import numpy as np

with open("Lab Session Data(Purchase data).csv", newline="") as f:
    reader = csv.reader(f)
    feature_names = np.array(next(reader))

X = feature_names[1:]
print(X)

['Candies (#)' 'Mangoes (Kg)' 'Milk Packets (#)' 'Payment (Rs)']


In [33]:
# Size of feature vecotr
X.size

4

In [35]:
# Dimnesion of the data vector
Y.shape

(10, 4)

In [37]:
#Rank of the matrix Y
int(lin.matrix_rank(Y))

3

In [38]:
lin.matrix_rank(X)

1

In [43]:
#Cost per unit of the product
# Extract quantities of products (Candies, Mangoes, Milk Packets) as matrix A
A = Y[:, :3]
# Extract total payment as vector b
b = Y[:, 3]

# Calculate the pseudo-inverse of A
A_inv = lin.pinv(A)

# Calculate the cost per unit of each product
cost_per_unit = A_inv @ b

cost_per_unit

array([ 1., 55., 18.])

In [44]:

for p, c in zip(X, cost_per_unit):
    print(f"{p}: Rs. {c:.2f}")

Candies (#): Rs. 1.00
Mangoes (Kg): Rs. 55.00
Milk Packets (#): Rs. 18.00


In [48]:
#A3
stock = pd.read_csv("IRCTC Stock Price.csv")
stock

,Date,Month,Day,Price,Open,High,Low,Volume,Chg%,Unnamed: 9,Unnamed: 10
0,"Jun 29, 2021",Jun,Tue,"2,081.85","2,092.00","2,126.90","2,065.05",1.67M,0.20%,NaN,NaN
1,"Jun 28, 2021",Jun,Mon,"2,077.75","2,084.00","2,112.45","2,068.40",707.73K,0.43%,NaN,NaN
2,"Jun 25, 2021",Jun,Fri,"2,068.85","2,084.35","2,088.50","2,053.10",475.82K,-0.20%,NaN,NaN
3,"Jun 24, 2021",Jun,Thu,"2,072.95","2,098.00","2,098.00","2,066.00",541.51K,-0.26%,NaN,NaN
4,"Jun 23, 2021",Jun,Wed,"2,078.25","2,102.00","2,111.40","2,072.00",809.62K,-0.23%,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN


In [51]:
# Remove N/A data present in price column
price_data = stock['Price'].str.replace(',', '').to_numpy(dtype=float)
price_data = price_data[~np.isnan(price_data)]
price_data

array([2081.85, 2077.75, 2068.85, 2072.95, 2078.25, 2083.  , 2076.85,
       2011.7 , 2050.4 , 2089.95, 2097.95, 2064.4 , 2093.75, 2106.35,
       2071.2 , 2144.85, 2094.8 , 1921.7 , 1921.8 , 1917.95, 1894.6 ,
       1903.2 , 1896.25, 1928.35, 1894.05, 1907.95, 1884.5 , 1862.  ,
       1855.65, 1858.1 , 1835.05, 1762.1 , 1747.65, 1746.6 , 1792.3 ,
       1748.65, 1693.4 , 1725.2 , 1723.65, 1770.2 , 1765.55, 1791.4 ,
       1792.55, 1795.85, 1793.2 , 1730.85, 1712.  , 1673.05, 1640.05,
       1612.7 , 1627.45, 1608.1 , 1611.65, 1582.  , 1730.9 , 1726.4 ,
       1709.  , 1688.55, 1702.65, 1751.75, 1757.  , 1755.25, 1747.4 ,
       1721.85, 1760.55, 1842.15, 1838.05, 1855.45, 1766.65, 1824.  ,
       1904.05, 1947.05, 1987.35, 2018.5 , 2026.7 , 2015.45, 1940.85,
       1961.1 , 1886.1 , 1897.65, 1938.45, 1759.65, 1726.95, 1675.45,
       1632.9 , 1615.85, 1675.4 , 1701.2 , 1698.65, 1674.15, 1713.1 ,
       1731.9 , 1619.  , 1618.4 , 1641.75, 1618.7 , 1555.  , 1518.9 ,
       1469.35, 1470

In [56]:
int(np.mean(price_data))

1560

In [55]:
int(np.var(price_data))

58496

In [62]:
# My own mean calculation
print(mean(price_data))

1560.6634538152598


In [65]:
# My own variance calculation
print(variance(price_data))

58496.49239931618


In [66]:
# Filter for 'Wed' (Wednesday) data
wednesday_stock = stock[stock['Day'] == 'Wed']

# Extract and clean 'Price' data for Wednesdays
wednesday_price_data = wednesday_stock['Price'].str.replace(',', '').to_numpy(dtype=float)
wednesday_price_data = wednesday_price_data[~np.isnan(wednesday_price_data)]

# Calculate the mean of Wednesday prices using the custom mean function
mean_wednesday_price = mean(wednesday_price_data)

print(f"Mean price on Wednesdays: {mean_wednesday_price:.2f}")

Mean price on Wednesdays: 1550.71


In [68]:
# Filter for April  data
april_stock = stock[stock['Month'] == 'Apr']


april_price_data = april_stock['Price'].str.replace(',', '').to_numpy(dtype=float)
april_price_data = april_price_data[~np.isnan(april_price_data)]

april_mean_price = mean(april_price_data)

print(f"Mean price in April: {april_mean_price:.2f}")

Mean price in April: 1698.95


In [70]:
# Extract 'Chg%' column
chg_percent_data = stock['Chg%']

# Clean the data: remove '%' sign, convert to float, and drop NaN values
# Apply a lambda function to remove '%' and convert to float, coercing errors to NaN
chg_percent_numeric = chg_percent_data.apply(lambda x: float(x.strip('%')) if isinstance(x, str) else np.nan)
chg_percent_numeric = chg_percent_numeric.dropna()

# Count the number of negative values (losses) using a lambda function
negative_changes = chg_percent_numeric[chg_percent_numeric.apply(lambda x: x < 0)]

# Calculate the probability of a loss
probability_of_loss = len(negative_changes) / len(chg_percent_numeric)

print(f"Total valid 'Chg%' entries: {len(chg_percent_numeric)}")
print(f"Number of negative 'Chg%' entries (losses): {len(negative_changes)}")
print(f"Probability of making a loss: {probability_of_loss:.4f}")

Total valid 'Chg%' entries: 249
Number of negative 'Chg%' entries (losses): 124
Probability of making a loss: 0.4980


In [76]:
# Probability of making profit on wednesday
wed_chg = stock[stock['Day'] == 'Wed']['Chg%']
wed_chg = wed_chg.apply(lambda x: float(x.strip('%')) if isinstance(x, str) else np.nan)
wed_chg.to_numpy()
change_count = wed_chg.size
pos_change = wed_chg[wed_chg > 0]
pos_change_count = pos_change.size

neg_change = wed_chg[wed_chg < 0]
neg_change_count = neg_change.size
neg_change_count

probability_of_loss = neg_change_count / change_count
probability_of_loss

probability_of_profit = 1 - probability_of_loss
probability_of_profit

0.42000000000000004